<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'khanamiryan/qrcode-detector-decoder' => array(
            'pretty_version' => '1.0.5.2',
            'version' => '1.0.5.2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../khanamiryan/qrcode-detector-decoder',
            'aliases' => array(),
            'reference' => '04fdd58d86a387065f707dc6d3cc304c719910c1',
            'dev_requirement' => false,
        ),
        'sheetdb/sheetdb-php' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sheetdb/sheetdb-php',
            'aliases' => array(),
            'reference' => '1cc8d76e6377adcce71f8c58f3de1f2e3a146e8d',
            'dev_requirement' => false,
        ),
    ),
);
